### ISSUE TITLE
test

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/Eigengrau#1]
please close out this issue to confirm access.

**Comment by ctgonzal** [comment]
Joined!
Should I be able to see the Close Issue button? I can't seem to find it...

**Comment by tokkentakker** [comment]
please try again, should look like this

![image](https://cloud.githubusercontent.com/assets/6943484/9441346/8b3a062e-4a43-11e5-9b95-64deb44c69db.png)
